idk some changes.

diff --git a/.local/bin/setbg b/.local/bin/setbg
--- a/.local/bin/setbg
+++ b/.local/bin/setbg
@@ -8,16 +8,13 @@
 # Location of link to wallpaper link.
 BGLOC="${XDG_DATA_HOME:-$HOME/.local/share/}/background"
 
-# Dunst process (for notify)
-ps -C dunst > /dev/null 2>&1 && RESULT='Activated'
-
 TRUELOC="$(readlink -f "$1")" &&
 case "$(file --mime-type -b "$TRUELOC")" in
     image/* ) ln -sf "$(readlink -f "$1")" "$BGLOC"
-        [ "$RESULT" = "Activated" ] && notify-send -i "$BGLOC" "Changing wallpaper..." ;;
+        [ "$RESULT" = "Activated" ] && echo "Changing wallpaper..." ;;
 	inode/directory ) ln -sf "$(fd --type=f .\(jpg\|jpeg\|png\|gif\) "$TRUELOC" | shuf -n 1)" "$BGLOC"
-        [ "$RESULT" = "Activated" ] && notify-send -i "$BGLOC" "Random Wallpaper chosen." ;;
-	*)  [ "$RESULT" = "Activated" ] && notify-send "Error" "Not a valid image." ; exit 1 ;;
+        [ "$RESULT" = "Activated" ] && echo "Random Wallpaper chosen." ;;
+	*)  [ "$RESULT" = "Activated" ] && echo "Error. Not a valid image." ; exit 1 ;;
 esac
 
 if [ "$XDG_SESSION_TYPE" = 'wayland' ]; then
@@ -25,6 +22,4 @@ if [ "$XDG_SESSION_TYPE" = 'wayland' ]; then
     export SWWW_TRANSITION_FPS=60
     export SWWW_TRANSITION_STEP=2
     swww img "$BGLOC"
-else
-    xwallpaper --zoom "$BGLOC"
 fi
